---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
```

# **Global Perspective On Risk Factors Associated with Adolescent Birth Rate**

By Hannah Miller and Shyhiem Lawrence

*MSUM Quantitative Biology Students*

Adolescent birth rate is the amount of births per 1000 females who give birth between the ages 15 to 19. There are many possible factors that could contribute to a high rate of adolescent birth. A high adolescent birth rate could result in mortality for both mothers and infants while this is possible factors such as truncated education, lower future family income and larger family size are also effects of adolescent birth. If we can understand the relationships between risk factors and adolescent birth rate , then we can make recommendations about how to reduce adolescent birth. But, we don't know enough about those relationships.The focus of this project is to explore the characteristics of countries that experienced high adolescent birth rate and to see how the frequency of those characteristics varied geographically. To do that, we will use data from the World Health Organization - Global Health Organization which contains information about the countries and their birth rates throughout the years 2000 to 2019. Investigation obtained from this data will be used to provide adequate information in high risk areas for adolescent birth rate.

**Methods**

**Results**

**Discussion**

**References:**

"Adolescent Birth Rate (per 1000 Women Aged 15-19 Years)." *World Health Organization*, THE GLOBAL HEALTH OBSERVATOR, <https://www.who.int/data/gho/data/indicators/indicator-details/GHO/adolescent-birth-rate-(per-1000-women-aged-15-19-years).>

"Adolescent Pregnancy." *World Health Organization*, World Health Organization, <https://www.who.int/news-room/fact-sheets/detail/adolescent-pregnancy.>

**Acknowledgements**

## 
